#!/bin/bash

# https://askubuntu.com/a/39732
# located in /etc/cron.hourly

# $1 is the path to the base data file
# $2 is the path to the node update script

PATH=/usr/local/bin:/usr/bin:/bin

prev=`tail -n1 $1  | tr '\t' '\n' | head -n1`
next=$((prev+1))

echo "running node script with $2 $next"
node $2 $next temp.tsv

echo "\nstacking $1 and temp.tsv"
csvstack $1 temp.tsv > temp2.tsv
cp temp2.tsv $1

echo "sorting $1 by date"
(head -n1 temp2.tsv && tail -n+2 temp2.tsv | sort -t$'\t' -r -n -k9 ) > temp3.tsv

echo "putting to aws"
aws s3api put-object --bucket orchidex --key data.tsv --body temp3.tsv
rm temp.tsv temp2.tsv temp3.tsv
